# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faiss.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x61iss.proto\"I\n\x10\x63heck_db_request\x12\x11\n\tdataset_n\x18\x01 \x01(\t\x12\x11\n\tchunk_len\x18\x02 \x01(\x05\x12\x0f\n\x07index_n\x18\x03 \x01(\t\"$\n\x11\x63heck_db_response\x12\x0f\n\x07is_okay\x18\x01 \x01(\x08\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"2\n\x0eSearchResponse\x12\x10\n\x08\x63ontexts\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\x32i\n\x05\x46\x61iss\x12\x33\n\x08\x63heck_db\x12\x11.check_db_request\x1a\x12.check_db_response\"\x00\x12+\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faiss_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECK_DB_REQUEST']._serialized_start=15
  _globals['_CHECK_DB_REQUEST']._serialized_end=88
  _globals['_CHECK_DB_RESPONSE']._serialized_start=90
  _globals['_CHECK_DB_RESPONSE']._serialized_end=126
  _globals['_SEARCHREQUEST']._serialized_start=128
  _globals['_SEARCHREQUEST']._serialized_end=173
  _globals['_SEARCHRESPONSE']._serialized_start=175
  _globals['_SEARCHRESPONSE']._serialized_end=225
  _globals['_FAISS']._serialized_start=227
  _globals['_FAISS']._serialized_end=332
# @@protoc_insertion_point(module_scope)
