# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import faiss_pb2 as faiss__pb2


class FaissStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.check_db = channel.unary_unary(
                '/Faiss/check_db',
                request_serializer=faiss__pb2.check_db_request.SerializeToString,
                response_deserializer=faiss__pb2.check_db_response.FromString,
                )
        self.Search = channel.unary_unary(
                '/Faiss/Search',
                request_serializer=faiss__pb2.SearchRequest.SerializeToString,
                response_deserializer=faiss__pb2.SearchResponse.FromString,
                )


class FaissServicer(object):
    """Missing associated documentation comment in .proto file."""

    def check_db(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaissServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'check_db': grpc.unary_unary_rpc_method_handler(
                    servicer.check_db,
                    request_deserializer=faiss__pb2.check_db_request.FromString,
                    response_serializer=faiss__pb2.check_db_response.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=faiss__pb2.SearchRequest.FromString,
                    response_serializer=faiss__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Faiss', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Faiss(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def check_db(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Faiss/check_db',
            faiss__pb2.check_db_request.SerializeToString,
            faiss__pb2.check_db_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Faiss/Search',
            faiss__pb2.SearchRequest.SerializeToString,
            faiss__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
